
main() {
  throw Exception("some exception!");
  
  throw 'Hello, this message was thrown.'; // we throw our own error
}